assessment_mctmgad/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^mappe/(?P<pk>[0-9]+)/ny$', views.MCTMGADCreateView.as_view(), name='mctmgad_create'),
    url(r'^detalj/(?P<pk>[0-9]+)$', views.MCTMGADDetailView.as_view(), name='mctmgad_detail'),
    url(r'^endre/(?P<pk>[0-9]+)$', views.MCTMGADUpdateView.as_view(), name='mctmgad_update')
]

assessments/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views
import assessment_abcde.urls
import assessment_bdi.urls
import assessment_bai.urls
import assessment_pswq.urls
import assessment_prs.urls
import assessment_mctmgad.urls
import assessment_mctmd.urls
import assessment_bcf.urls


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^mappe/(?P<pk>[0-9]+)/$', views.FolderDetailView.as_view(), name='folder_detail'),
    url(r'^mappe/endre/(?P<pk>[0-9]+)/$', views.FolderUpdateView.as_view(), name='folder_update'),
    url(r'^mappe/slette/(?P<pk>[0-9]+)/$', views.FolderDeleteView.as_view(), name='folder_delete'),
    url(r'^mappe/ny$', views.FolderCreateView.as_view(), name='folder_create'),
    url(r'^abcde/', include(assessment_abcde.urls)),
    url(r'^bdi/', include(assessment_bdi.urls)),
    url(r'^bai/', include(assessment_bai.urls)),
    url(r'^pswq/', include(assessment_pswq.urls)),
    url(r'^prs/', include(assessment_prs.urls)),
    url(r'^mctmgad/', include(assessment_mctmgad.urls)),
    url(r'^mctmd/', include(assessment_mctmd.urls)),
    url(r'^bcf/', include(assessment_bcf.urls))
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

import user.urls
import assessments.urls
import sfiles.urls
from aboutpage.views import AboutPageView
from whitewash.views import upload_file


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='start.html'), name='index'),
    url(r'^omsiden/$', AboutPageView.as_view(), name='aboutpage'),
    url(r'^vask/$', upload_file, name='whitewash'),
    url(r'^kartlegging/', include(assessments.urls, namespace='assessments')),
    url(r'^papir/', include(sfiles.urls, namespace='sfiles')),
    url(r'^bruker/', include(user.urls, namespace='user'))
]

user/urls.py
# -*- coding: utf-8 -*-
"""
URLconf for registration and activation, using django-registration's
HMAC activation workflow.
"""

from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^bruker/(?P<pk>[0-9]+)$', views.Dashboard.as_view(), name="dashboard"),
    url(r'^aktiver/ferdig/$',
        TemplateView.as_view(
            template_name='user/activation_complete.html'
        ),
        name='registration_activation_complete'),
    # The activation key can make use of any character from the
    # URL-safe base64 alphabet, plus the colon as a separator.
    url(r'^aktiver/(?P<activation_key>[-:\w]+)/$',
        views.CustomActivationView.as_view(),
        name='registration_activate'),
    url(r'^ny/$',
        views.CustomRegistrationView.as_view(template_name='user/registration.html'),
        name='register'),
    url(r'^ny/ferdig/$',
        TemplateView.as_view(
            template_name='user/registration_complete.html'
        ),
        name='registration_complete'),
    url(r'^ny/stengt/$',
        TemplateView.as_view(
            template_name='user/registration_closed.html'
        ),
        name='registration_disallowed'),
    url(r'', include('user.auth_urls')),
]

assessment_mctmgad/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

from assessments.models import Folder

class MCTMGADModel(models.Model):
    date = models.DateTimeField(default=timezone.now)
    folder = models.ForeignKey(Folder, related_name='mctmgads')

    trigger = models.TextField(blank=True)
    type1_worry = models.TextField(blank=True)
    type2_worry = models.TextField(blank=True)
    positive_meta_beliefs = models.TextField(blank=True)
    negative_meta_beliefs = models.TextField(blank=True)
    behavior = models.TextField(blank=True)
    thought_control = models.TextField(blank=True)
    emotion = models.TextField(blank=True)


    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'MCT GAD kasusformulering'

    def get_absolute_url(self):
        return reverse('assessments:mctmgad_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '{}/{}/MCTMGAD-{}'.format(self.folder.user, self.folder.name, self.date)

assessment_mctmgad/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils import timezone

from .models import MCTMGADModel
from assessments.models import Folder


class MCTMGADCreateView(LoginRequiredMixin, generic.CreateView):
    model = MCTMGADModel
    template_name = 'assessment_mctmgad/mctmgad_create.html'
    fields = ['folder', 'trigger', 'type1_worry', 'type2_worry',
              'positive_meta_beliefs', 'negative_meta_beliefs', 
              'behavior', 'thought_control', 'emotion']

    def get(self, request, *args, **kwargs):
        folder = get_object_or_404(Folder, pk=self.kwargs['pk'])

        if folder.user != request.user:
            raise PermissionDenied
        else:
            return super(MCTMGADCreateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MCTMGADCreateView, self).get_context_data(**kwargs)
        context['from_folder'] = Folder.objects.get(pk=self.kwargs['pk'])
        context['other_folders'] = Folder.objects.filter(user=self.request.user).exclude(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.date = timezone.now()
        return super(MCTMGADCreateView, self).form_valid(form)


class MCTMGADDetailView(LoginRequiredMixin, generic.DetailView):
    model = MCTMGADModel
    template_name = 'assessment_mctmgad/mctmgad_detail.html'
    context_object_name = 'mctmgad'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Check if user is owner of content
        if self.object.folder.user != request.user:
            raise PermissionDenied
        else:
            return super(MCTMGADDetailView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        return redirect('assessments:folder_detail', self.object.folder.pk)


class MCTMGADUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = MCTMGADModel
    template_name = 'assessment_mctmgad/mctmgad_update.html'
    context_object_name = 'mctmgad'
    fields = ['folder', 'trigger', 'type1_worry', 'type2_worry',
              'positive_meta_beliefs', 'negative_meta_beliefs', 
              'behavior', 'thought_control', 'emotion']

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Check if user is owner of content
        if self.object.folder.user != request.user:
            raise PermissionDenied
        else:
            return super(MCTMGADUpdateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MCTMGADUpdateView, self).get_context_data(**kwargs)
        context['folders'] = Folder.objects.filter(user=self.request.user)
        return context

assessment_mctmgad/templates/assessment_mctmgad/mctmgad_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h2 id="top">MCTMGAD</h2>
      <h5>Metakognitiv modell for bekymring</h5>
      <form role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <hr/>
        <div class="form-group">
          <label for="id_trigger">
            <strong>Triggertanke</strong><br />
            <div class="help-text-muted">
              Hvilken tanke var det som utløste bekymringen?
            </div>
          </label> 
          <textarea class="form-control" rows="4" id="id_trigger" name="trigger"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_type1_worry">
            <strong>Bekymring</strong><br />
            <div class="help-text-muted">
              Hva var det som bekymret deg når du fikk denne tanken? Hva var innholdet i bekymringstankene?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_type1_worry" name="type1_worry"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_emotion">
            <strong>Følelser</strong><br />
            <div class="help-text-muted">
              Hvilke følelser dukket opp når du bekymret deg for dette? Hvilke symptomer fikk du? Fikk du angst? Hvilke symptomer merket du?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_emotion" name="emotion"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_type2_worry">
            <strong>Tanker om bekymring</strong><br />
            <div class="help-text-muted">
              Når du fikk disse følelsene eller symptomene, tenkte du at det kom til å skje noe fælt som følge av disse bekymringene? Hva er det verste som kan skje hvis du fortsatte å bekymre deg?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_type2_worry" name="type2_worry"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_negative_meta_beliefs">
            <strong>Negative antakelser om bekymring</strong><br />
            <div class="help-text-muted">
              Tror du at bekymring lar seg kontrollere?<br/>
              Tenker du at det på noen måte er negativt å bekymre seg? Kan bekymringen være skadelig for deg?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_negative_meta_beliefs" name="negative_meta_beliefs"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_positive_meta_beliefs">
            <strong>Positive antakelser om bekymring</strong><br />
            <div class="help-text-muted">
            Tenker du at bekymring kan ha noen nytte? Kan den for eksempel gjøre at du er mer forberedt hvis noe skulle oppstå?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_positive_meta_beliefs" name="positive_meta_beliefs"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_behavior">
            <strong>Handlinger</strong><br />
            <div class="help-text-muted">
            Når bekymringene kommer, gjør du noe for å stanse dem? Unngår du situasjoner eller ber du om forsikringer? Prøver du å finne ut om det er noe å bekymre seg for? Bruker du noen form for rusmidler?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_behavior" name="behavior"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_thought_control">
            <strong>Tankekontroll</strong><br />
            <div class="help-text-muted">
            Bruker du mer direkte strategier for å kontrollere bekyringene? Forsøker du å unngå ting som kan utløse bekymringer?<br />
            Har du noen gang forsøkt å stanse en bekymring ved å ikke gå inn i den akkurat da?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_thought_control" name="thought_control"></textarea>
        </div>

        <p><a href="#top">Tilbake til toppen</a></p>
    </div>
    
    <div class="col-md-4">
      <div class="form-group">
        <label for="id_folder">Mappe</label> 
        <select class="c-select form-control" id="id_folder" name="folder" required>
          <option value="{{ from_folder.pk}}" selected="selected">{{ from_folder.name }}</option>
          {% for folder in other_folders %}
          <option value="{{ folder.pk }}">{{ folder.name }}</option>
          {% endfor %}
        </select>
      </div>
      <input class="btn btn-custom" type="submit" value="Lagre MCTMGAD" />
      </form>
    </div>

  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=from_folder.pk %}">{{ from_folder.name }}</a>
  <li class="active">Ny MCTMD Kasusformulering</li>
</ol>
{% endblock %}

assessment_mctmgad/templates/assessment_mctmgad/mctmgad_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>MCTMGAD</h2>
      <h5>Metakognitiv modell for bekymring</h5>
      <div class="assessment-meta">
        <p>Mappe: <strong>{{ mctmgad.folder.name }}</strong></p>
        <p>Opprettet: <strong> {{ mctmgad.date|date:'j. F o' }}</strong></p>
      </div>
    </div>
    <div class="col-md-4">
      <a class="btn btn-custom m-b-1" href="{% url 'assessments:mctmgad_update' pk=mctmgad.pk %}">Endre</a>
      <a class="btn btn-custom-red m-b-1" data-toggle="modal" data-target="#delete-confirm">Slett</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <hr />

      <div class="assessment-ib w-100">
        Trigger <br />
        <div class="assessment-box">
          {{ mctmgad.trigger|linebreaks }}
        </div>
      </div>
  
      <p><i class="fa fa-arrow-down fa-2x"></i></p>

      <div class="assessment-ib w-40">
        Positive meta-antakelser <br />
        <div class="assessment-box border-dashed">
          {{ mctmgad.positive_meta_beliefs|linebreaks }}
        </div>
      </div>

      <i class="fa fa-arrow-right fa-2x"></i>

      <div class="assessment-ib w-40">
        Bekymring (type 1-bekymring) <br />
        <div class="assessment-box border-red">
          {{ mctmgad.type1_worry|linebreaks }}
        </div>
      </div>

      <p><i class="fa fa-arrow-down fa-2x"></i></p>

      <div class="assessment-ib w-40">
        Negative meta-antakelser <br />
        <div class="assessment-box border-dashed">
          {{ mctmgad.negative_meta_beliefs|linebreaks }}
        </div>
      </div>
      
      <i class="fa fa-arrow-right fa-2x"></i>
      
      <div class="assessment-ib w-40">
        Metabekymring (type 2-bekymring) <br />
        <div class="assessment-box">
          {{ mctmgad.type2_worry|linebreaks }}
        </div>
      </div>

      <div class="assessment-arrow"><i class="fa fa-arrow-down fa-2x"></i></div>

      <div class="assessment-ib w-33">
        Handlinger <br />
        <div class="assessment-box">
          {{ mctmgad.behavior|linebreaks }}
        </div>
      </div>

      <div class="assessment-ib w-33">
        Tankekontroll<br />
        <div class="assessment-box">
          {{ mctmgad.thought_control|linebreaks }}
        </div>
      </div>

      <div class="assessment-ib w-33">
        Følelser <br />
        <div class="assessment-box border-red">
          {{ mctmgad.emotion|linebreaks }}
        </div>
      </div>

    </div>

  </div>
</div>

<!-- Delete confirm modal -->
<div class="modal fade" id="delete-confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Lukk">
        <span aria-hidden="true">&times;</span>
      </button>
      <h5 class="modal-title" id="myModalLabel">Slette skjema?</h5>
    </div>
    <div class="modal-body">
      Bekreft at du vil slette <strong>MCTMGAD-skjema {{ mctmgad.date|date:'j. F o' }}</strong> lagret i {{ mctmgad.folder.name }}.
    </div>
    <div class="modal-footer">
      <form action="" method="post">
        {% csrf_token %}
        <button type="button" class="btn btn-custom" data-dismiss="modal">Avbryt</button>
        <input class="btn btn-custom-red" type="submit" value="Slett" />
      </form>
    </div>
   </div>
  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=mctmgad.folder.pk %}">{{ mctmgad.folder.name }}</a></li>
  <li class="active">MCTMGAD {{ mctmgad.date|date:'j. F o' }}</li>
</ol>
{% endblock %}

{% block printerfriendly %}
<a class="nocolor-link pull-right" href="#" onclick="window.print();"><i class="fa fa-print"></i></a>
{% endblock %}

assessment_mctmgad/templates/assessment_mctmgad/mctmgad_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h2 id="top">Endre MCTMGAD</h2>
      <h5>Metakognitiv modell for bekymring</h5>
      <div class="assessment-meta">
        <p>Mappe: <strong>{{ mctmgad.folder.name }}</strong></p>
        <p>Opprettet: <strong>{{ mctmgad.date|date:'j. F o' }}</strong></p>
      </div>
      <form role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
      <hr/>
        <div class="form-group">
          <label for="id_trigger">
            <strong>Triggertanke</strong><br />
            <div class="help-text-muted">
              Hvilken tanke var det som utløste bekymringen?
            </div>
          </label> 
          <textarea class="form-control" rows="4" id="id_trigger" name="trigger">{{ mctmgad.trigger }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_type1_worry">
            <strong>Bekymring</strong><br />
            <div class="help-text-muted">
              Hva var det som bekymret deg når du fikk denne tanken? Hva var innholdet i bekymringstankene?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_type1_worry" name="type1_worry">{{ mctmgad.type1_worry }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_emotion">
            <strong>Følelser</strong><br />
            <div class="help-text-muted">
              Hvilke følelser dukket opp når du bekymret deg for dette? Hvilke symptomer fikk du? Fikk du angst? Hvilke symptomer merket du?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_emotion" name="emotion">{{ mctmgad.emotion }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_type2_worry">
            <strong>Tanker om bekymring</strong><br />
            <div class="help-text-muted">
              Når du fikk disse følelsene eller symptomene, tenkte du at det kom til å skje noe fælt som følge av disse bekymringene? Hva er det verste som kan skje hvis du fortsatte å bekymre deg?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_type2_worry" name="type2_worry">{{ mctmgad.type2_worry }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_negative_meta_beliefs">
            <strong>Negative antakelser om bekymring</strong><br />
            <div class="help-text-muted">
              Tenker du at det på noen måte er negativt å bekymre seg? Kan bekymringen være skadelig for deg?<br />
              Tror du at bekymring lar seg kontrollere?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_negative_meta_beliefs" name="negative_meta_beliefs">{{ mctmgad.negative_meta_beliefs }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_positive_meta_beliefs">
            <strong>Positive antakelser om bekymring</strong><br />
            <div class="help-text-muted">
            Tenker du at bekymring kan ha noen nytte? Kan den for eksempel gjøre at du er mer forberedt hvis noe skulle oppstå?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_positive_meta_beliefs" name="positive_meta_beliefs">{{ mctmgad.positive_meta_beliefs }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_behavior">
            <strong>Handlinger</strong><br />
            <div class="help-text-muted">
            Når bekymringene kommer, gjør du noe for å stanse dem? Unngår du situasjoner eller ber du om forsikringer? Prøver du å finne ut om det er noe å bekymre seg for? Bruker du noen form for rusmidler?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_behavior" name="behavior">{{ mctmgad.behavior }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_thought_control">
            <strong>Tankekontroll</strong><br />
            <div class="help-text-muted">
            Bruker du mer direkte strategier for å kontrollere bekyringene? Forsøker du å unngå ting som kan utløse bekymringer?<br />
            Har du noen gang forsøkt å stanse en bekymring ved å ikke gå inn i den akkurat da?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_thought_control" name="thought_control">{{ mctmgad.thought_control }}</textarea>
        </div>

        <p><a href="#top">Tilbake til toppen</a></p>
      </div>
      <div class="col-md-4">
        <div class="form-group">
          <label for="id_folder">Mappe</label> 
            <select class="c-select form-control" id="id_folder" name="folder">
            {% for folder in folders %}
              <option value="{{ folder.pk }}"{% if mctmgad.folder == folder %} selected="selected"{% endif %}>{{ folder.name }}</option>
            {% endfor %}
            </select>
        </div>
        <input class="btn btn-custom" type="submit" value="Lagre endringer" />
        </form>
      </div>

  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=mctmgad.folder.pk %}">{{ mctmgad.folder.name }}</a></li>
  <li><a href="{% url 'assessments:mctmgad_detail' pk=mctmgad.pk %}">MCTMGAD {{ mctmgad.date|date:'j. F o' }}</a></li>
  <li class="active">Endre</li>
</ol>
{% endblock %}