assessment_bcf/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^mappe/(?P<pk>[0-9]+)/ny$', views.bcf_create_view, name='bcf_create'),
    url(r'^detalj/(?P<pk>[0-9]+)$', views.BCFDetailView.as_view(), name='bcf_detail'),
    # url(r'^endre/(?P<pk>[0-9]+)$', views.bcf_update_view, name='bcf_update'),
    # url(r'^mappe/(?P<pk>[0-9]+)/oppsummering$', views.BCFSummaryView.as_view(), 
    #     name='bcf_summary'),
]

assessments/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views
import assessment_abcde.urls
import assessment_bdi.urls
import assessment_bai.urls
import assessment_pswq.urls
import assessment_prs.urls
import assessment_mctmgad.urls
import assessment_mctmd.urls
import assessment_bcf.urls


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^mappe/(?P<pk>[0-9]+)/$', views.FolderDetailView.as_view(), name='folder_detail'),
    url(r'^mappe/endre/(?P<pk>[0-9]+)/$', views.FolderUpdateView.as_view(), name='folder_update'),
    url(r'^mappe/slette/(?P<pk>[0-9]+)/$', views.FolderDeleteView.as_view(), name='folder_delete'),
    url(r'^mappe/ny$', views.FolderCreateView.as_view(), name='folder_create'),
    url(r'^abcde/', include(assessment_abcde.urls)),
    url(r'^bdi/', include(assessment_bdi.urls)),
    url(r'^bai/', include(assessment_bai.urls)),
    url(r'^pswq/', include(assessment_pswq.urls)),
    url(r'^prs/', include(assessment_prs.urls)),
    url(r'^mctmgad/', include(assessment_mctmgad.urls)),
    url(r'^mctmd/', include(assessment_mctmd.urls)),
    url(r'^bcf/', include(assessment_bcf.urls))
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

import user.urls
import assessments.urls
import sfiles.urls
from aboutpage.views import AboutPageView
from whitewash.views import upload_file


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='start.html'), name='index'),
    url(r'^omsiden/$', AboutPageView.as_view(), name='aboutpage'),
    url(r'^vask/$', upload_file, name='whitewash'),
    url(r'^kartlegging/', include(assessments.urls, namespace='assessments')),
    url(r'^papir/', include(sfiles.urls, namespace='sfiles')),
    url(r'^bruker/', include(user.urls, namespace='user'))
]

user/urls.py
# -*- coding: utf-8 -*-
"""
URLconf for registration and activation, using django-registration's
HMAC activation workflow.
"""

from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^bruker/(?P<pk>[0-9]+)$', views.Dashboard.as_view(), name="dashboard"),
    url(r'^aktiver/ferdig/$',
        TemplateView.as_view(
            template_name='user/activation_complete.html'
        ),
        name='registration_activation_complete'),
    # The activation key can make use of any character from the
    # URL-safe base64 alphabet, plus the colon as a separator.
    url(r'^aktiver/(?P<activation_key>[-:\w]+)/$',
        views.CustomActivationView.as_view(),
        name='registration_activate'),
    url(r'^ny/$',
        views.CustomRegistrationView.as_view(template_name='user/registration.html'),
        name='register'),
    url(r'^ny/ferdig/$',
        TemplateView.as_view(
            template_name='user/registration_complete.html'
        ),
        name='registration_complete'),
    url(r'^ny/stengt/$',
        TemplateView.as_view(
            template_name='user/registration_closed.html'
        ),
        name='registration_disallowed'),
    url(r'', include('user.auth_urls')),
]

assessment_bcf/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

from assessments.models import Folder


class BCFModel(models.Model):
    date = models.DateTimeField(default=timezone.now)
    folder = models.ForeignKey(Folder, related_name='bcfs')

    relevant_childhood_data = models.TextField(blank=True)
    core_beliefs = models.TextField(blank=True)
    conditional_assumptions = models.TextField(blank=True)
    coping_strategies = models.TextField(blank=True)

    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'Beck kasusformuleringer'

    def get_absolute_url(self):
        return reverse('assessments:bcf_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '{}/{}/BCF-{}'.format(self.folder.user, self.folder.name, self.date)

class BCFExtraModel(models.Model):
    parent_model = models.ForeignKey(BCFModel)

    situation = models.TextField(blank=True)
    automatic_thought = models.TextField(blank=True)
    meaning_automatic_thought = models.TextField(blank=True)
    emotion = models.TextField(blank=True)
    behavior = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = 'ABC-skjema'

    def __str__(self):
        return '{}/{}'.format(self.parent_model, self.situation)

assessment_bcf/forms.py
from django import forms

class BCFExtraForm(forms.Form):
    situation = forms.CharField(required=False)
    automatic_thought = forms.CharField(required=False)
    meaning_automatic_thought = forms.CharField(required=False)
    emotion = forms.CharField(required=False)
    behavior = forms.CharField(required=False)

assessment_bcf/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.forms import modelform_factory, formset_factory
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.db import transaction, IntegrityError

from .models import BCFModel, BCFExtraModel
from .forms import BCFExtraForm
from assessments.models import Folder

@login_required
def bcf_create_view(request, pk):
    folder = get_object_or_404(Folder, pk=pk)

    if folder.user != request.user:
        raise PermissionDenied

    # Generate forms
    BCFForm = modelform_factory(BCFModel, exclude=('date',))
    BCFFormSet = formset_factory(BCFExtraForm, extra=1)

    if request.method == 'POST':
        bcf_form = BCFForm(request.POST)

        if bcf_form.is_valid():
            new_bcf_form = bcf_form.save(commit=False)
            new_bcf_form.date = timezone.now()
            new_bcf_form.save()

            bcf_extra_form = BCFFormSet(request.POST, prefix='bcf_extra')

            if bcf_extra_form.is_valid():
                bcf_extra_data = []
                
                for field in bcf_extra_form:
                    situation = field.cleaned_data.get('situation')
                    automatic_thought = field.cleaned_data.get('automatic_thought')
                    meaning_automatic_thought = field.cleaned_data.get('meaning_automatic_thought')
                    emotion = field.cleaned_data.get('emotion')
                    behavior = field.cleaned_data.get('behavior')

                    bcf_extra_data.append(BCFExtraModel(
                        parent_model=new_bcf_form,
                        situation=situation,
                        automatic_thought=automatic_thought,
                        meaning_automatic_thought=meaning_automatic_thought,
                        emotion=emotion,
                        behavior=behavior))

                # Bulk save form date to extra model
                try:
                    with transaction.atomic():
                        BCFExtraModel.objects.bulk_create(bcf_extra_data)
                
                except IntegrityError:
                    print('IntegrityError')

            else:
                print('Extra not valid')

        return redirect('assessments:bcf_detail', new_bcf_form.pk)

    else:
        bcf_form = BCFForm()
        bcf_extra_form = BCFFormSet(prefix='bcf_extra')

        other_folders = Folder.objects.filter(user=request.user).exclude(pk=pk)

        context = {
            'bcf_form': bcf_form,
            'bcf_extra_form': bcf_extra_form,
            'from_folder': folder,
            'other_folders': other_folders
        }

        return render(request, 'assessment_bcf/bcf_create.html', context)


class BCFDetailView(LoginRequiredMixin, generic.DetailView):
    model = BCFModel
    template_name = 'assessment_bcf/bcf_detail.html'
    context_object_name = 'bcf'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Check if user is owner of content
        if self.object.folder.user != request.user:
            raise PermissionDenied
        else:
            return super(BCFDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(BCFDetailView, self).get_context_data(**kwargs)
        context['bcf_extra'] = BCFExtraModel.objects.filter(
            parent_model=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        return redirect('assessments:folder_detail', self.object.folder.pk)

assessment_bcf/templates/assessment_bcf/bcf_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h2 id="top">Beck kasusformulering</h2>
      <hr />

      <form name="abcde" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
          <label for="id_relevant_childhood_data">
            <strong>Relevante barndomsdata</strong><br />
            <div class="help-text-muted">
              Relevante opplysninger om oppvekst, familie.
            </div>
          </label> 
          <textarea class="form-control" rows="3" id="id_relevant_childhood_data" name="relevant_childhood_data"></textarea>
        </div>

        <div class="form-group">
          <label for="id_core_beliefs">
            <strong>Grunnleggende leveregler</strong><br />
            <div class="help-text-muted">
              Grunnleggende leveregler.
            </div>
          </label> 
          <textarea class="form-control" rows="3" id="id_core_beliefs" name="core_beliefs"></textarea>
        </div>

        <div class="form-group">
          <label for="id_conditional_assumptions">
            <strong>Sekundære leveregler</strong><br />
            <div class="help-text-muted">
              Sekundære leveregler
            </div>
          </label> 
          <textarea class="form-control" rows="3" id="id_conditional_assumptions" name="conditional_assumptions"></textarea>
        </div>

        <div class="form-group">
          <label for="id_coping_strategies">
            <strong>Kompensatoriske strategier</strong><br />
            <div class="help-text-muted">
              Kompensatoriske strategier
            </div>
          </label> 
          <textarea class="form-control" rows="3" id="id_coping_strategies" name="coping_strategies"></textarea>
        </div>

        
        {% for form in bcf_extra_form %}
      <div class="dynamic-bcf">

        <div class="form-group">
          <label for="{{ form.situation.id_for_label }}">
            <strong>Situasjon</strong><br />
            <div class="help-text-muted">
              Situasjon
            </div>
          </label> 
          <textarea class="form-control" rows="1" id="{{ form.situation.id_for_label }}" name="bcf_extra-{{ forloop.counter0 }}-situation"></textarea>
        </div>

        <div class="form-group">
          <label for="{{ form.automatic_thought.id_for_label }}">
            <strong>Automatisk tanke</strong><br />
            <div class="help-text-muted">
              Automatisk tanke
            </div>
          </label> 
          <textarea class="form-control" rows="1" id="{{ form.automatic_thought.id_for_label }}" name="bcf_extra-{{ forloop.counter0 }}-automatic_thought"></textarea>
        </div>

        <div class="form-group">
          <label for="{{ form.meaning_automatic_thought.id_for_label }}">
            <strong>Mening med automatisk tanke</strong><br />
            <div class="help-text-muted">
              Mening med automatisk tanke
            </div>
          </label> 
          <textarea class="form-control" rows="1" id="{{ form.meaning_automatic_thought.id_for_label }}" name="bcf_extra-{{ forloop.counter0 }}-meaning_automatic_thought"></textarea>
        </div>

        <div class="form-group">
          <label for="{{ form.emotion.id_for_label }}">
            <strong>Følelse</strong><br />
            <div class="help-text-muted">
              Følelse
            </div>
          </label> 
          <textarea class="form-control" rows="1" id="{{ form.emotion.id_for_label }}" name="bcf_extra-{{ forloop.counter0 }}-emotion"></textarea>
        </div>

        <div class="form-group">
          <label for="{{ form.behavior.id_for_label }}">
            <strong>Atferd</strong><br />
            <div class="help-text-muted">
              Atferd
            </div>
          </label> 
          <textarea class="form-control" rows="1" id="{{ form.behavior.id_for_label }}" name="bcf_extra-{{ forloop.counter0 }}-behavior"></textarea>
        </div>
      






      </div>



        {% endfor %}
        {{ bcf_extra_form.management_form }}


    


    </div>

    <div class="col-md-4">
      <div class="form-group">
        <label for="id_folder">Mappe</label> 
        <select class="c-select form-control" id="id_folder" name="folder" required>
          <option value="{{ from_folder.pk}}" selected="selected">{{ from_folder.name }}</option>
          {% for folder in other_folders %}
          <option value="{{ folder.pk }}">{{ folder.name }}</option>
          {% endfor %}
        </select>
      </div>
      <input class="btn btn-custom" type="submit" value="Lagre kasusformulering" />
    </form>
    </div>
  
  </div>
</div>


{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=from_folder.pk %}">{{ from_folder.name }}</a></li>
  <li class="active">Ny kasusformulering</li>
</ol>
{% endblock %}

{% block js_extras %}
<script src="{% static 'js/jquery.formset.js' %}"></script>
<script>
    $('.dynamic-bcf').formset({
        prefix: '{{ bcf_extra_form.prefix }}',
        addText: '<i class="fa fa-plus-square-o fa-lg"></i> Legg til',
        deleteText: '<i class="fa fa-minus-square-o fa-lg"></i>',
        addCssClass: 'nocolor-link',        
        deleteCssClass: 'nocolor-link'
    });
</script>
{% endblock %}

assessment_bcf/templates/assessment_bcf/bcf_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load prs_extras %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>Beck kasusformulering</h2>
      <div class="assessment-meta">
        <p>Mappe: <strong>{{ bcf.folder.name }}</strong></p>
        <p>Opprettet: <strong> {{ bcf.date|date:'j. F o' }}</strong></p>
      </div>
    </div>
    <div class="col-md-4">
      <a class="btn btn-custom m-b-1" href="">Endre</a>
      <a class="btn btn-custom-red m-b-1" data-toggle="modal" data-target="#delete-confirm">Slett</a>
    </div>

    <div class="row">
      <div class="col-md-12">
        <hr />
        <strong>Relevante barndomsdata</strong><br />
        <div class="assessment-box m-b-2">
        {{ bcf.relevant_childhood_data }}
        </div>

        <strong>Grunnleggende leveregler</strong><br />
        <div class="assessment-box m-b-2">
          {{ bcf.core_beliefs }}
        </div>

        <strong>Senkundære leveregler</strong><br />
        <div class="assessment-box m-b-2">
          {{ bcf.conditional_assumptions }}
        </div>

        <strong>Kompensatoriske strategier</strong><br />
        <div class="assessment-box m-b-2">
          {{ bcf.coping_strategies }}
        </div>

        {% for bcf in bcf_extra %}

        <strong>Situasjon</strong><br />
        <div class="assessment-box">
          {{ bcf.situation }}
        </div>

        <strong>Automatisk tanke</strong><br />
        <div class="assessment-box">
        {{ bcf.automatic_thought }}
        </div>

        <strong>Meningen med automatisk tanke</strong><br />
        <div class="assessment-box">
         {{ bcf.meaning_automatic_thought }}
          </div>
        {% endfor %}
        
    
    </div>
  </div>
</div>

<!-- Delete confirm modal -->
<div class="modal fade" id="delete-confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Lukk">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title" id="myModalLabel">Bekreft</h4>
    </div>
    <div class="modal-body">
      Bekreft at du vil slette <strong> Beck kasusformulering {{ bcf.date|date:'j. F o' }}</strong> lagret i {{ bcf.folder.name }}.
    </div>
    <div class="modal-footer">
      <form action="" method="post">
        {% csrf_token %}
        <button type="button" class="btn btn-custom" data-dismiss="modal">Avbryt</button>
        <input class="btn btn-custom-red" type="submit" value="Slett" />
      </form>
    </div>
   </div>
  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=bcf.folder.pk %}">{{ bcf.folder.name }}</a></li>
  <li class="active">BCF {{ bcf.date|date:'j. F o' }}</li>
</ol>
{% endblock %}

{% block printerfriendly %}
<a class="nocolor-link pull-right" href="#" onclick="window.print();"><i class="fa fa-print"></i></a>
{% endblock %}