assessment_mctmd/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^mappe/(?P<pk>[0-9]+)/ny$', views.MCTMDCreateView.as_view(), name='mctmd_create'),
    url(r'^detalj/(?P<pk>[0-9]+)$', views.MCTMDDetailView.as_view(), name='mctmd_detail'),
    url(r'^endre/(?P<pk>[0-9]+)$', views.MCTMDUpdateView.as_view(), name='mctmd_update')
]

assessments/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views
import assessment_abcde.urls
import assessment_bdi.urls
import assessment_bai.urls
import assessment_pswq.urls
import assessment_prs.urls
import assessment_mctmgad.urls
import assessment_mctmd.urls
import assessment_bcf.urls


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^mappe/(?P<pk>[0-9]+)/$', views.FolderDetailView.as_view(), name='folder_detail'),
    url(r'^mappe/endre/(?P<pk>[0-9]+)/$', views.FolderUpdateView.as_view(), name='folder_update'),
    url(r'^mappe/slette/(?P<pk>[0-9]+)/$', views.FolderDeleteView.as_view(), name='folder_delete'),
    url(r'^mappe/ny$', views.FolderCreateView.as_view(), name='folder_create'),
    url(r'^abcde/', include(assessment_abcde.urls)),
    url(r'^bdi/', include(assessment_bdi.urls)),
    url(r'^bai/', include(assessment_bai.urls)),
    url(r'^pswq/', include(assessment_pswq.urls)),
    url(r'^prs/', include(assessment_prs.urls)),
    url(r'^mctmgad/', include(assessment_mctmgad.urls)),
    url(r'^mctmd/', include(assessment_mctmd.urls)),
    url(r'^bcf/', include(assessment_bcf.urls))
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

import user.urls
import assessments.urls
import sfiles.urls
from aboutpage.views import AboutPageView
from whitewash.views import upload_file


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='start.html'), name='index'),
    url(r'^omsiden/$', AboutPageView.as_view(), name='aboutpage'),
    url(r'^vask/$', upload_file, name='whitewash'),
    url(r'^kartlegging/', include(assessments.urls, namespace='assessments')),
    url(r'^papir/', include(sfiles.urls, namespace='sfiles')),
    url(r'^bruker/', include(user.urls, namespace='user'))
]

user/urls.py
# -*- coding: utf-8 -*-
"""
URLconf for registration and activation, using django-registration's
HMAC activation workflow.
"""

from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^bruker/(?P<pk>[0-9]+)$', views.Dashboard.as_view(), name="dashboard"),
    url(r'^aktiver/ferdig/$',
        TemplateView.as_view(
            template_name='user/activation_complete.html'
        ),
        name='registration_activation_complete'),
    # The activation key can make use of any character from the
    # URL-safe base64 alphabet, plus the colon as a separator.
    url(r'^aktiver/(?P<activation_key>[-:\w]+)/$',
        views.CustomActivationView.as_view(),
        name='registration_activate'),
    url(r'^ny/$',
        views.CustomRegistrationView.as_view(template_name='user/registration.html'),
        name='register'),
    url(r'^ny/ferdig/$',
        TemplateView.as_view(
            template_name='user/registration_complete.html'
        ),
        name='registration_complete'),
    url(r'^ny/stengt/$',
        TemplateView.as_view(
            template_name='user/registration_closed.html'
        ),
        name='registration_disallowed'),
    url(r'', include('user.auth_urls')),
]

assessment_mctmd/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

from assessments.models import Folder

class MCTMDModel(models.Model):
    date = models.DateTimeField(default=timezone.now)
    folder = models.ForeignKey(Folder, related_name='mctmds')

    trigger = models.TextField(blank=True)
    rumination = models.TextField(blank=True)
    positive_meta_beliefs = models.TextField(blank=True)
    negative_meta_beliefs = models.TextField(blank=True)
    depression_behavior = models.TextField(blank=True)
    depression_thoughts = models.TextField(blank=True)
    depression_affect = models.TextField(blank=True)


    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'MCT Depresjon kasusformulering'

    def get_absolute_url(self):
        return reverse('assessments:mctmd_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '{}/{}/MCTMD-{}'.format(self.folder.user, self.folder.name, self.date)

assessment_mctmd/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils import timezone

from .models import MCTMDModel
from assessments.models import Folder


class MCTMDCreateView(LoginRequiredMixin, generic.CreateView):
    model = MCTMDModel
    template_name = 'assessment_mctmd/mctmd_create.html'
    fields = ['folder', 'trigger', 'rumination', 'positive_meta_beliefs',
              'negative_meta_beliefs', 'depression_behavior',
              'depression_thoughts', 'depression_affect']

    def get(self, request, *args, **kwargs):
        folder = get_object_or_404(Folder, pk=self.kwargs['pk'])

        if folder.user != request.user:
            raise PermissionDenied
        else:
            return super(MCTMDCreateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MCTMDCreateView, self).get_context_data(**kwargs)
        context['from_folder'] = Folder.objects.get(pk=self.kwargs['pk'])
        context['other_folders'] = Folder.objects.filter(user=self.request.user).exclude(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.date = timezone.now()
        return super(MCTMDCreateView, self).form_valid(form)

class MCTMDDetailView(LoginRequiredMixin, generic.DetailView):
    model = MCTMDModel
    template_name = 'assessment_mctmd/mctmd_detail.html'
    context_object_name = 'mctmd'
    
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Check if user is owner of content
        if self.object.folder.user != request.user:
            raise PermissionDenied
        else:
            return super(MCTMDDetailView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()

        return redirect('assessments:folder_detail', self.object.folder.pk)


class MCTMDUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = MCTMDModel
    template_name = 'assessment_mctmd/mctmd_update.html'
    context_object_name = 'mctmd'
    fields = ['folder', 'trigger', 'rumination', 'positive_meta_beliefs',
              'negative_meta_beliefs', 'depression_behavior',
              'depression_thoughts', 'depression_affect']

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Check if user is owner of content
        if self.object.folder.user != request.user:
            raise PermissionDenied
        else:
            return super(MCTMDUpdateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(MCTMDUpdateView, self).get_context_data(**kwargs)
        context['folders'] = Folder.objects.filter(user=self.request.user)
        return context

assessment_mctmd/templates/assessment_mctmd/mctmd_create.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h2 id="top">MCTMD</h2>
      <h5>Metakognitiv modell for depresjon</h5>
      <form role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <hr/>
        <div class="form-group">
          <label for="id_trigger">
            <strong>Triggertanke</strong><br />
            <div class="help-text-muted">
              Hva var den første tanken du hadde som startet grublingen?
            </div>
          </label> 
          <textarea class="form-control" rows="2" id="id_trigger" name="trigger"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_rumination">
            <strong>Grubling</strong><br />
            <div class="help-text-muted">
              Hva tenkte du etter du fikk triggertanken? Hva grublet du på?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_rumination" name="rumination"></textarea>
        </div>

        <hr />
        <div class="form-group">
        <strong>Resultat av grubling</strong><br />

          <label for="id_depression_affect">
            <div class="help-text-muted">
              Hva skjedde med humøret/følelsene dine etter grublingen?
            </div>
          </label>
          <textarea class="form-control" rows="2" id="id_depression_affect" name="depression_affect"></textarea>

          <label for="id_depression_thoughts">
            <div class="help-text-muted">
              Hva endte du opp med å tenke etter grublingen?
            </div>
          </label>
          <textarea class="form-control" rows="2" id="id_depression_thoughts" name="depression_thoughts"></textarea>
          
          <label for="id_depression_behavior">
            <div class="help-text-muted">
              Hvilket effekt hadde grublingen på handlingene dine?
            </div>
          </label>
          <textarea class="form-control" rows="2" id="id_depression_behavior" name="depression_behavior"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <strong>Antakelser om grubling</strong><br />

          <label for="id_negative_meta_beliefs">
            <div class="help-text-muted">
              Negative antakelser om grubling. Føler du at du har kontroll over grublingen? På en skala fra 0 - 100 hvor mye tror du på antakelsen?
            </div>
          </label>
          <textarea class="form-control" rows="3" id="id_negative_meta_beliefs" name="negative_meta_beliefs"></textarea>

          <label for="id_positive_meta_beliefs">
            <div class="help-text-muted">
              Positive antakelser om grubling
            </div>
          </label>
          <textarea class="form-control" rows="3" id="id_positive_meta_beliefs" name="positive_meta_beliefs"></textarea>
        </div>




        <p><a href="#top">Tilbake til toppen</a></p>
    </div>
    
    <div class="col-md-4">
      <div class="form-group">
        <label for="id_folder">Mappe</label> 
        <select class="c-select form-control" id="id_folder" name="folder" required>
          <option value="{{ from_folder.pk}}" selected="selected">{{ from_folder.name }}</option>
          {% for folder in other_folders %}
          <option value="{{ folder.pk }}">{{ folder.name }}</option>
          {% endfor %}
        </select>
      </div>
      <input class="btn btn-custom" type="submit" value="Lagre MCTMD" />
      </form>
    </div>

  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=from_folder.pk %}">{{ from_folder.name }}</a>
  <li class="active">Ny MCTMD Kasusformulering</li>
</ol>
{% endblock %}

assessment_mctmd/templates/assessment_mctmd/mctmd_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>MCTMD</h2>
      <h5>Metakognitiv modell for depresjon</h5>
      <div class="assessment-meta">
        <p>Mappe: <strong>{{ mctmd.folder.name }}</strong></p>
        <p>Opprettet: <strong> {{ mctmd.date|date:'j. F o' }}</strong></p>
      </div>

    </div>
    <div class="col-md-4">
      <a class="btn btn-custom m-b-1" href="{% url 'assessments:mctmd_update' pk=mctmd.pk %}">Endre</a>
      <a class="btn btn-custom-red m-b-1" data-toggle="modal" data-target="#delete-confirm">Slett</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <hr />
      <strong>Triggertanke</strong><br />
      <div class="assessment-box border-blue">
        {{ mctmd.trigger|linebreaks }}
      </div>

      <div class="assessment-arrow">
        <i class="fa fa-arrow-down fa-3x"></i>
      </div>
      
      <strong>Positive meta-antakelser</strong><br />
      <div class="assessment-box border-dashed">
        {{ mctmd.positive_meta_beliefs|linebreaks }}
      </div>

      <div class="assessment-arrow">
        <i class="fa fa-arrow-down fa-3x"></i>
      </div>

      <strong>Grubling</strong><br />
      <div class="assessment-box border-red">
        {{ mctmd.rumination|linebreaks }}
      </div>

      <div class="assessment-arrow">
        <i class="fa fa-arrow-down fa-3x"></i>
      </div>

      <strong>Negative meta-antakelser</strong><br />
      <div class="assessment-box border-dashed">
        {{ mctmd.negative_meta_beliefs|linebreaks }}
      </div>

      <div class="assessment-arrow">
        <i class="fa fa-arrow-down fa-3x"></i>
      </div>

      <strong>Depresjon</strong>
      <div class="row">
        <div class="col-md-4">
          <em>Atferd</em><br />
          <div class="assessment-box border-blue">
              {{ mctmd.depression_behavior|linebreaks }}
          </div>
        </div>
        <div class="col-md-4">
          <em>Tanker</em><br />
          <div class="assessment-box">
            {{ mctmd.depression_thoughts|linebreaks }}
          </div>
        </div>
        <div class="col-md-4">
          <em>Følelser</em><br />
          <div class="assessment-box border-red">
            {{ mctmd.depression_affect|linebreaks }}
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

<!-- Delete confirm modal -->
<div class="modal fade" id="delete-confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Lukk">
        <span aria-hidden="true">&times;</span>
      </button>
      <h5 class="modal-title" id="myModalLabel">Slette skjema?</h5>
    </div>
    <div class="modal-body">
      Bekreft at du vil slette <strong>MCTMD-skjema {{ mctmd.date|date:'j. F o' }}</strong> lagret i {{ mctmd.folder.name }}.
    </div>
    <div class="modal-footer">
      <form action="" method="post">
        {% csrf_token %}
        <button type="button" class="btn btn-custom" data-dismiss="modal">Avbryt</button>
        <input class="btn btn-custom-red" type="submit" value="Slett" />
      </form>
    </div>
   </div>
  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=mctmd.folder.pk %}">{{ mctmd.folder.name }}</a></li>
  <li class="active">MCTMD {{ mctmd.date|date:'j. F o' }}</li>
</ol>
{% endblock %}

{% block printerfriendly %}
<a class="nocolor-link pull-right" href="#" onclick="window.print();"><i class="fa fa-print"></i></a>
{% endblock %}

assessment_mctmd/templates/assessment_mctmd/mctmd_update.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h2 id="top">Endre MCTMD</h2>
      <h5>Metakognitiv modell for depresjon</h5>
      <div class="assessment-meta">
        <p>Mappe: <strong>{{ mctmd.folder.name }}</strong></p>
        <p>Opprettet: <strong>{{ mctmd.date|date:'j. F o' }}</strong></p>
      </div>
      <form role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <hr/>
        <div class="form-group">
          <label for="id_trigger">
            <strong>Triggertanke</strong><br />
            <div class="help-text-muted">
              Hva var den første tanken du hadde som startet grublingen?
            </div>
          </label> 
          <textarea class="form-control" rows="2" id="id_trigger" name="trigger">{{ mctmd.trigger }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_rumination">
            <strong>Grubling</strong><br />
            <div class="help-text-muted">
              Hva tenkte du etter du fikk triggertanken? Hva grublet du på?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_rumination" name="rumination">{{ mctmd.rumination }}</textarea>
        </div>

        <hr />
        <div class="form-group">
        <strong>Resultat av grubling</strong><br />

          <label for="id_depression_affect">
            <div class="help-text-muted">
              Hva skjedde med humøret/følelsene dine etter grublingen?
            </div>
          </label>
          <textarea class="form-control" rows="2" id="id_depression_affect" name="depression_affect">{{ mctmd.depression_affect }}</textarea>

          <label for="id_depression_thoughts">
            <div class="help-text-muted">
              Hva endte du opp med å tenke etter grublingen?
            </div>
          </label>
          <textarea class="form-control" rows="2" id="id_depression_thoughts" name="depression_thoughts">{{ mctmd.depression_thoughts }}</textarea>
          
          <label for="id_depression_behavior">
            <div class="help-text-muted">
              Hvilket effekt hadde grublingen på handlingene dine?
            </div>
          </label>
          <textarea class="form-control" rows="2" id="id_depression_behavior" name="depression_behavior">{{ mctmd.depression_behavior }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <strong>Antakelser om grubling</strong><br />

          <label for="id_negative_meta_beliefs">
            <div class="help-text-muted">
              Negative antakelser om grubling. Føler du at du har kontroll over grublingen? På en skala fra 0 - 100 hvor mye tror du på antakelsen?
            </div>
          </label>
          <textarea class="form-control" rows="3" id="id_negative_meta_beliefs" name="negative_meta_beliefs">{{ mctmd.negative_meta_beliefs }}</textarea>

          <label for="id_positive_meta_beliefs">
            <div class="help-text-muted">
              Positive antakelser om grubling
            </div>
          </label>
          <textarea class="form-control" rows="3" id="id_positive_meta_beliefs" name="positive_meta_beliefs">{{ mctmd.positive_meta_beliefs }}</textarea>
        </div>
        <p><a href="#top">Tilbake til toppen</a></p>
    </div>
    
    <div class="col-md-4">
      <div class="form-group">
        <label for="id_folder">Mappe</label> 
        <select class="c-select form-control" id="id_folder" name="folder">
          {% for folder in folders %}
            <option value="{{ folder.pk }}"{% if mctmd.folder == folder %} selected="selected"{% endif %}>{{ folder.name }}</option>
          {% endfor %}
        </select>
      </div>
      <input class="btn btn-custom" type="submit" value="Lagre endringer" />
      </form>
    </div>

  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=mctmd.folder.pk %}">{{ mctmd.folder.name }}</a></li>
  <li><a href="{% url 'assessments:mctmd_detail' pk=mctmd.pk %}">MCTMD {{ mctmd.date|date:'j. F o' }}</a></li>
  <li class="active">Endre</li>
</ol>
{% endblock %}