assessment_abcde/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^mappe/(?P<pk>[0-9]+)/ny$', views.ABCDECreateView.as_view(), name='abcde_create'),
    url(r'^detalj/(?P<pk>[0-9]+)$', views.ABCDEDetailView.as_view(), name='abcde_detail'),
    url(r'^endre/(?P<pk>[0-9]+)$', views.ABCDEUpdateView.as_view(), name='abcde_update')
]

assessments/urls.py
from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views
import assessment_abcde.urls
import assessment_bdi.urls
import assessment_bai.urls
import assessment_pswq.urls
import assessment_prs.urls
import assessment_mctmgad.urls
import assessment_mctmd.urls
import assessment_bcf.urls


urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^mappe/(?P<pk>[0-9]+)/$', views.FolderDetailView.as_view(), name='folder_detail'),
    url(r'^mappe/endre/(?P<pk>[0-9]+)/$', views.FolderUpdateView.as_view(), name='folder_update'),
    url(r'^mappe/slette/(?P<pk>[0-9]+)/$', views.FolderDeleteView.as_view(), name='folder_delete'),
    url(r'^mappe/ny$', views.FolderCreateView.as_view(), name='folder_create'),
    url(r'^abcde/', include(assessment_abcde.urls)),
    url(r'^bdi/', include(assessment_bdi.urls)),
    url(r'^bai/', include(assessment_bai.urls)),
    url(r'^pswq/', include(assessment_pswq.urls)),
    url(r'^prs/', include(assessment_prs.urls)),
    url(r'^mctmgad/', include(assessment_mctmgad.urls)),
    url(r'^mctmd/', include(assessment_mctmd.urls)),
    url(r'^bcf/', include(assessment_bcf.urls))
]

config/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

import user.urls
import assessments.urls
import sfiles.urls
from aboutpage.views import AboutPageView
from whitewash.views import upload_file


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='start.html'), name='index'),
    url(r'^omsiden/$', AboutPageView.as_view(), name='aboutpage'),
    url(r'^vask/$', upload_file, name='whitewash'),
    url(r'^kartlegging/', include(assessments.urls, namespace='assessments')),
    url(r'^papir/', include(sfiles.urls, namespace='sfiles')),
    url(r'^bruker/', include(user.urls, namespace='user'))
]

user/urls.py
# -*- coding: utf-8 -*-
"""
URLconf for registration and activation, using django-registration's
HMAC activation workflow.
"""

from django.conf.urls import include, url
from django.views.generic.base import TemplateView

from . import views


urlpatterns = [
    url(r'^bruker/(?P<pk>[0-9]+)$', views.Dashboard.as_view(), name="dashboard"),
    url(r'^aktiver/ferdig/$',
        TemplateView.as_view(
            template_name='user/activation_complete.html'
        ),
        name='registration_activation_complete'),
    # The activation key can make use of any character from the
    # URL-safe base64 alphabet, plus the colon as a separator.
    url(r'^aktiver/(?P<activation_key>[-:\w]+)/$',
        views.CustomActivationView.as_view(),
        name='registration_activate'),
    url(r'^ny/$',
        views.CustomRegistrationView.as_view(template_name='user/registration.html'),
        name='register'),
    url(r'^ny/ferdig/$',
        TemplateView.as_view(
            template_name='user/registration_complete.html'
        ),
        name='registration_complete'),
    url(r'^ny/stengt/$',
        TemplateView.as_view(
            template_name='user/registration_closed.html'
        ),
        name='registration_disallowed'),
    url(r'', include('user.auth_urls')),
]

assessment_abcde/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

from assessments.models import Folder


class ABCDEModel(models.Model):
    date = models.DateTimeField(default=timezone.now)
    folder = models.ForeignKey(Folder, related_name='abcdes')

    activating_event = models.TextField(blank=True)
    beliefs = models.TextField(blank=True)
    logical_fallacies = models.TextField(blank=True)
    consequences = models.TextField(blank=True)
    dispute = models.TextField(blank=True)
    effects = models.TextField(blank=True)

    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'ABDCDE-skjemaer'

    def get_absolute_url(self):
        return reverse('assessments:abcde_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return '{}/{}/ABCDE-{}'.format(self.folder.user,self.folder.name, self.date)

assessment_abcde/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse, reverse_lazy
from django.utils import timezone

from assessments.utils import check_user
from .models import ABCDEModel
from assessments.models import Folder


class ABCDECreateView(LoginRequiredMixin, generic.CreateView):
    model = ABCDEModel
    template_name = 'assessment_abcde/abcde_create.html'
    fields = ['folder', 'activating_event', 'beliefs',
              'logical_fallacies', 'consequences', 'dispute', 'effects']
    
    def get(self, request, *args, **kwargs):
        self.folder = get_object_or_404(Folder, pk=self.kwargs['pk'])
        request = check_user(request, self.folder.user)
        return super(ABCDECreateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ABCDECreateView, self).get_context_data(**kwargs)
        context['from_folder'] = self.folder
        context['other_folders'] = Folder.objects.filter(
            user=self.request.user).exclude(pk=self.folder.pk)
        return context

    def form_valid(self, form):
        form.instance.date = timezone.now()
        return super(ABCDECreateView, self).form_valid(form)

class ABCDEDetailView(LoginRequiredMixin, generic.DetailView):
    model = ABCDEModel
    template_name = 'assessment_abcde/abcde_detail.html'
    context_object_name = 'abcde'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        request = check_user(request, self.object.folder.user)
        return super(ABCDEDetailView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect('assessments:folder_detail', self.object.folder.pk)


class ABCDEUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = ABCDEModel
    template_name = 'assessment_abcde/abcde_update.html'
    context_object_name = 'abcde'
    fields = ['folder', 'activating_event', 'beliefs',
              'logical_fallacies', 'consequences', 'dispute', 'effects']

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # Check if user is owner of content
        if self.object.folder.user != request.user:
            raise PermissionDenied
        else:
            return super(ABCDEUpdateView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ABCDEUpdateView, self).get_context_data(**kwargs)
        context['folders'] = Folder.objects.filter(user=self.request.user)
        return context

assessment_abcde/templates/assessment_abcde/abcde_create.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js_extras %}
    <script src="{% static 'js/abcde.js' %}"></script>
{% endblock %}


{% block content %}
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h2 id="top">ABCDE-skjema</h2>
      <form name="abcde" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <hr/>
        <div class="form-group">
          <label for="id_activating_event">
            <strong>A - Situasjon</strong><br />
            <div class="help-text-muted">
              Beskriv hva som skjedde.
            </div>
          </label> 
          <textarea class="form-control" rows="2" id="id_activating_event" name="activating_event"></textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_beliefs">
            <strong>B - Tanker</strong><br />
            <div class="help-text-muted">
              <ul class="list-unstyled">
                <li>Hvilke tanker eller bilder dukker opp i hodet i situasjonen (A)?</li>
                <li>Ranger hvor mye du tror på tanken(e) 0 - 10.</li>
              </ul>
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_beliefs" name="beliefs"></textarea>
        </div>


        <hr />
        <div class="form-group">
          <label for="id_consequences">
            <strong>C - Konsekvenser</strong><br />
            <div class="help-text-muted">
              <ul class="list-unstyled">
                <li>Hvilke følelser dukker opp, hvordan reagerer kroppen, hva gjorde du etter (B)? Konsekvensen av å tolke situasjonen på måten du gjør (B)?</li>
                <li>Ranger styrke på følelser 0 - 10</li>
              </ul>
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_consequences" name="consequences"></textarea>

        <hr />
        <div class="form-group">
          <label for="id_dispute">
            <strong>D - Alternative tanker</strong><br />
            <div class="help-text-muted">
              <ul class="list-unstyled">
                <li> Hva ville du sagt til en venn dersom han eller hun hadde den negative tanken (B).</li>
                <li>Er det noe som motbeviser tanken (B)?</li>
                <li>Er (B) en objektiv måte å se det på?</li>
              </ul>
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_dispute" name="dispute"></textarea>


          <label for="id_logical_fallacies">
            D - Tankefeil
            <div class="help-text-muted">
              <ul class="list-unstyled">
                <li>Eventuelle tankefeil som ble brukt i B.</li>
              </ul>
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_logical_fallacies" name="logical_fallacies"></textarea>
          <div class="help-text-muted">
            <div id="fallacies">
              <a class="btn btn-custom-small" data-filter=".mentaltfilter">Mentalt filter</a>  
              <a class="btn btn-custom-small" data-filter=".altingenting">Alt-eller-ingenting</a>
              <a class="btn btn-custom-small" data-filter=".overgeneralisering">Overgeneralisering</a>
              <a class="btn btn-custom-small" data-filter=".diskvalifisering">Diskvalifisering</a>
              <a class="btn btn-custom-small" data-filter=".tankelesning">Tankelesning</a>
              <a class="btn btn-custom-small" data-filter=".overmini">Overdrive/minimalisere</a>
              <a class="btn btn-custom-small" data-filter=".emores">Emosjonell resonnering</a>
              <a class="btn btn-custom-small" data-filter=".burdeskulle">Burde-skulle-må</a>
              <a class="btn btn-custom-small" data-filter=".stempling">Stempling</a>
              <a class="btn btn-custom-small" data-filter=".persbeb">Personliggjøring og bebreidelse</a>
            </div>
            
            <div class="fallacies-spacer">
            <div id="fallacies-info">
              <p class="mentaltfilter">
                Dette innebærer at du dveler ved det negative og ignorerer det positive.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Mentalt filter">Legg til</a>

              </p>

              <p class="altingenting">
                Alt-eller-ingenting (sort-hvitt tenkning). Dette innebærer at du har lett for å kategorisere noe eller noen som enten svært bra eller svært dårlig, uten å være bevisst at det finnes gråtoner mellom sort og hvitt.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Alt-eller-ingenting">Legg til</a>
              </p>
              
              <p class="overgeneralisering">
                Innebærer at du ser på en negativ hendelse som et endeløst mønster av nederlag. Det føles som om alt går galt for deg, når det i realiteten kun er enkelthendelser som ikke gikk etter planen.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Overgeneralisering">Legg til</a>
              </p>
              <p class="diskvalifisering">
                Diskvalifisering og mentalt filter er overlappende tankefeller, men til forskjell fra mentalt filter innebærer denne tankefellen at negativiteten er rettet mot deg selv. Du insisterer på at det du har oppnådd i livet og dine positive egenskaper ikke teller.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Diskvalifisering">Legg til</a>
              </p>
              <p class="tankelesning">
                Dette innebærer å «trekke forhastede konklusjoner» og består av to deler: «tankelesning» og «spådomskunst». Tankelesning er når du tar det for gitt at folk reagerer negativt på deg, selv om det ikke finnes noe definitivt bevis for det.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Tankelesning">Legg til</a>
              </p>
              <p class="overmini">
                Dette betyr at du gjerne overdriver eller reduserer betydningen av enkelte ting i helt urimelig grad.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Overdrive/minimalisere">Legg til</a>
              </p>
              <p class="emores">
                Dette innebærer at du faller i den fellen å tro at du er hva du føler.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Emosjonell resonnering">Legg til</a>
              </p>
              <p class="burdeskulle">
                Dette innebærer at du benytter ord som burde, skulle eller må for å kritisere deg selv eller andre.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Burde-skulle-må">Legg til</a>
              </p>
              <p class="stempling">
                Innebærer at du identifiserer deg selv eller andre med et eller flere feiltrinn. I stedet for å si til deg selv i en gitt situasjon at «jeg gjorde en feil», sier du til deg selv at «jeg er en taper». Et slikt negativt stempel resulterer uunngåelig i redusert selvfølelse og selvtillit.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Stempling">Legg til</a>
              </p>
              <p class="persbeb">
                Dette kan handle om at du utelukkende bebreider andre for en gitt problematikk og dermed overser hvordan dine egne holdninger og din egen atferd kan ha bidratt til problemet. Foruten denne formen for ansvarsfraskrivelse, kan du på den annen side bebreide deg selv for problematikk som du ikke er ansvarlig for.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Personliggjøring eller bebreidelse">Legg til</a>
              </p>
            </div>
            </div>

          </div>
        </div>
        
        <hr />
        <div class="form-group">
          <label for="id_effects">
            <strong>E - Effekt av alternativ tanke</strong><br />
            <div class="help-text-muted">
              Hva skjedde etter at du brukte den alternative tanken (D)?
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_effects" name="effects"></textarea>
        </div>
      </div>

        <p><a href="#top">Tilbake til toppen</a></p>
    </div>
    
    <div class="col-md-4">
      <div class="form-group">
        <label for="id_folder">Mappe</label> 
        <select class="c-select form-control" id="id_folder" name="folder" required>
          <option value="{{ from_folder.pk}}" selected="selected">{{ from_folder.name }}</option>
          {% for folder in other_folders %}
          <option value="{{ folder.pk }}">{{ folder.name }}</option>
          {% endfor %}
        </select>
      </div>
      <input class="btn btn-custom" type="submit" value="Lagre ABCDE" />
      </form>
    </div>

  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=from_folder.pk %}">{{ from_folder.name }}</a>
  <li class="active">Nytt ABCDE-skjema</li>
</ol>
{% endblock %}

assessment_abcde/templates/assessment_abcde/abcde_detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <h2>ABCDE-skjema</h2>
      <div class="assessment-meta">
        <p>Mappe: <strong>{{ abcde.folder.name }}</strong></p>
        <p>Opprettet: <strong> {{ abcde.date|date:'j. F o' }}</strong></p>
      </div>
    </div>
    <div class="col-md-4">
      <a class="btn btn-custom" href="{% url 'assessments:abcde_update' pk=abcde.pk %}">Endre</a>
      <a class="btn btn-custom-red" data-toggle="modal" data-target="#delete-confirm">Slett</a>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <hr />
      <strong>A - Situasjon</strong><br />
      <div class="assessment-box">
        {{ abcde.activating_event|linebreaks }}
      </div>

      <div class="assessment-arrow">
        <i class="fa fa-arrow-down fa-3x"></i>
      </div>
      
      <strong>B - Negative automatiske tanker</strong><br />
      <div class="assessment-box border-red">
        {{ abcde.beliefs|linebreaks }}
      </div>

      <div class="assessment-arrow">
        <i class="fa fa-arrow-down fa-3x"></i>
      </div>

      <strong>C - Konsekvenser av negative automatiske tanker</strong><br />
      <div class="assessment-box border-red">
        {{ abcde.consequences|linebreaks }}
      </div>

      <div class="assessment-arrow">
        <i class="fa fa-arrow-down fa-3x"></i>
      </div>

      <strong>D - Alternative tanker</strong><br />
      <div class="assessment-box border-blue">
        {{ abcde.dispute|linebreaks }}
        {% if abcde.logical_fallacies %}
        <br />
        <strong>Tankefeil</strong>
        {{abcde.logical_fallacies|linebreaks }}
        {% endif %}
      </div>

      <div class="assessment-arrow">
        <i class="fa fa-arrow-down fa-3x"></i>
      </div>

      <strong>E - Effekt av alternativ tanke</strong><br />
      <div class="assessment-box border-blue">
        {{ abcde.effects|linebreaks }}
      </div>

    </div>
  </div>
</div>

<!-- Delete confirm modal -->
<div class="modal fade" id="delete-confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Lukk">
        <span aria-hidden="true">&times;</span>
      </button>
      <h5 class="modal-title" id="myModalLabel">Slette skjema?</h5>
    </div>
    <div class="modal-body">
      Bekreft at du vil slette <strong>ABCDE-skjema {{ abcde.date|date:'j. F o' }}</strong> lagret i {{ abcde.folder.name }}.
    </div>
    <div class="modal-footer">
      <form action="" method="post">
        {% csrf_token %}
        <button type="button" class="btn btn-custom" data-dismiss="modal">Avbryt</button>
        <input class="btn btn-custom-red" type="submit" value="Slett" />
      </form>
    </div>
   </div>
  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=abcde.folder.pk %}">{{ abcde.folder.name }}</a></li>
  <li class="active">ABCDE {{ abcde.date|date:'j. F o' }}</li>
</ol>
{% endblock %}

{% block printerfriendly %}
<a class="nocolor-link pull-right" href="#" onclick="window.print();"><i class="fa fa-print"></i></a>
{% endblock %}

assessment_abcde/templates/assessment_abcde/abcde_update.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block js_extras %}
    <script src="{% static 'js/abcde.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">

    <div class="col-md-8">
      <h2 id="top">Endre ABCDE</h2>
      <h5>ABCDE-skjema</h5>
      <div class="assessment-meta">
        <p>Mappe: <strong>{{ abcde.folder.name }}</strong></p>
        <p>Opprettet: <strong>{{ abcde.date|date:'j. F o' }}</strong></p>
      </div>
       <form name="abcde" role="form" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <hr/>
        <div class="form-group">
          <label for="id_activating_event">
            <strong>A - Situasjon</strong><br />
            <div class="help-text-muted">
              Situasjon
            </div>
          </label> 
          <textarea class="form-control" rows="2" id="id_activating_event" name="activating_event">{{ abcde.activating_event }}</textarea>
        </div>

        <hr />
        <div class="form-group">
          <label for="id_beliefs">
            <strong>B - Negative automatiske tanker</strong><br />
            <div class="help-text-muted">
              Tanker
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_beliefs" name="beliefs">{{ abcde.beliefs }}</textarea>
        </div>


        <hr />
        <div class="form-group">
          <label for="id_consequences">
            <strong>C - Konsekvenser</strong><br />
            <div class="help-text-muted">
              Konsekvenser av de negative automatiske tankene.
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_consequences" name="consequences">{{ abcde.consequences }}</textarea>

        <hr />
        <div class="form-group">
          <label for="id_dispute">
            <strong>D - Alternative tanker</strong><br />
            <div class="help-text-muted">
              Hva er alternative tanker til dette.
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_dispute" name="dispute">{{ abcde.dispute }}</textarea>


          <label for="id_logical_fallacies">
            D - Tankefeil
            <div class="help-text-muted">
             Tankefeil er greit å ha med.
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_logical_fallacies" name="logical_fallacies">{{ abcde.logical_fallacies }}</textarea>
          <div class="help-text-muted">
            <div id="fallacies">
              <a class="btn btn-custom-small" data-filter=".mentaltfilter">Mentalt filter</a>  
              <a class="btn btn-custom-small" data-filter=".altingenting">Alt-eller-ingenting</a>
              <a class="btn btn-custom-small" data-filter=".overgeneralisering">Overgeneralisering</a>
              <a class="btn btn-custom-small" data-filter=".diskvalifisering">Diskvalifisering</a>
              <a class="btn btn-custom-small" data-filter=".tankelesning">Tankelesning</a>
              <a class="btn btn-custom-small" data-filter=".overmini">Overdrive/minimalisere</a>
              <a class="btn btn-custom-small" data-filter=".emores">Emosjonell resonnering</a>
              <a class="btn btn-custom-small" data-filter=".burdeskulle">Burde-skulle-må</a>
              <a class="btn btn-custom-small" data-filter=".stempling">Stempling</a>
              <a class="btn btn-custom-small" data-filter=".persbeb">Personliggjøring og bebreidelse</a>
            </div>
            
            <div class="fallacies-spacer">
            <div id="fallacies-info">
              <p class="mentaltfilter">
                Dette innebærer at du dveler ved det negative og ignorerer det positive.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Mentalt filter">Legg til</a>

              </p>

              <p class="altingenting">
                Alt-eller-ingenting (sort-hvitt tenkning). Dette innebærer at du har lett for å kategorisere noe eller noen som enten svært bra eller svært dårlig, uten å være bevisst at det finnes gråtoner mellom sort og hvitt.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Alt-eller-ingenting">Legg til</a>
              </p>
              
              <p class="overgeneralisering">
                Innebærer at du ser på en negativ hendelse som et endeløst mønster av nederlag. Det føles som om alt går galt for deg, når det i realiteten kun er enkelthendelser som ikke gikk etter planen.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Overgeneralisering">Legg til</a>
              </p>
              <p class="diskvalifisering">
                Diskvalifisering og mentalt filter er overlappende tankefeller, men til forskjell fra mentalt filter innebærer denne tankefellen at negativiteten er rettet mot deg selv. Du insisterer på at det du har oppnådd i livet og dine positive egenskaper ikke teller.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Diskvalifisering">Legg til</a>
              </p>
              <p class="tankelesning">
                Dette innebærer å «trekke forhastede konklusjoner» og består av to deler: «tankelesning» og «spådomskunst». Tankelesning er når du tar det for gitt at folk reagerer negativt på deg, selv om det ikke finnes noe definitivt bevis for det.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Tankelesning">Legg til</a>
              </p>
              <p class="overmini">
                Dette betyr at du gjerne overdriver eller reduserer betydningen av enkelte ting i helt urimelig grad.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Overdrive/minimalisere">Legg til</a>
              </p>
              <p class="emores">
                Dette innebærer at du faller i den fellen å tro at du er hva du føler.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Emosjonell resonnering">Legg til</a>
              </p>
              <p class="burdeskulle">
                Dette innebærer at du benytter ord som burde, skulle eller må for å kritisere deg selv eller andre.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Burde-skulle-må">Legg til</a>
              </p>
              <p class="stempling">
                Innebærer at du identifiserer deg selv eller andre med et eller flere feiltrinn. I stedet for å si til deg selv i en gitt situasjon at «jeg gjorde en feil», sier du til deg selv at «jeg er en taper». Et slikt negativt stempel resulterer uunngåelig i redusert selvfølelse og selvtillit.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Stempling">Legg til</a>
              </p>
              <p class="persbeb">
                Dette kan handle om at du utelukkende bebreider andre for en gitt problematikk og dermed overser hvordan dine egne holdninger og din egen atferd kan ha bidratt til problemet. Foruten denne formen for ansvarsfraskrivelse, kan du på den annen side bebreide deg selv for problematikk som du ikke er ansvarlig for.
                <a class="btn btn-custom-small-blue" href="#" data-fallacy="Personliggjøring eller bebreidelse">Legg til</a>
              </p>
            </div>
            </div>

          </div>
        </div>
        
        <hr />
        <div class="form-group">
          <label for="id_effects">
            <strong>E - Effekt av alternativ tanke</strong><br />
            <div class="help-text-muted">
              Hva skjedde etter at du brukte den alternative tanken.
            </div>
          </label>
          <textarea class="form-control" rows="4" id="id_effects" name="effects">{{ abcde.effects }}</textarea>
        </div>
      </div>

        <p><a href="#top">Tilbake til toppen</a></p>
    </div>
    
    <div class="col-md-4">
      <div class="form-group">
        <label for="id_folder">Mappe</label> 
        <select class="c-select form-control" id="id_folder" name="folder">
          {% for folder in folders %}
            <option value="{{ folder.pk }}"{% if mctmd.folder == folder %} selected="selected"{% endif %}>{{ folder.name }}</option>
          {% endfor %}
        </select>
      </div>
      <input class="btn btn-custom" type="submit" value="Lagre endringer" />
      </form>
    </div>

  </div>
</div>
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb-custom">
  <li><a href="{% url 'index' %}">Start</a></li>
  <li><a href="{% url 'assessments:index' %}">Kartlegging</a></li>
  <li><a href="{% url 'assessments:folder_detail' pk=abcde.folder.pk %}">{{ abcde.folder.name }}</a></li>
  <li><a href="{% url 'assessments:abcde_detail' pk=abcde.pk %}">ABCDE {{ abcde.date|date:'j. F o' }}</a></li>
  <li class="active">Endre</li>
</ol>
{% endblock %}